spring:
  application:
    name: ms-venta

---
# Perfil local (XAMPP)
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:mysql://localhost:3306/db_ecomarket
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
logging:
  file:
    name: logs/ms-venta.log
  level:
    root: INFO
    com.example.MicroVenta: DEBUG
server:
  port: 8085
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

    ---
# Perfil docker
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false
server:
  port: ${PORT:8083}
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://ms-eureka:8761/eureka}
  instance:
    prefer-ip-address: true