spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_ecomarket
    username: root
    password: ""
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

server:
  port: 8085

eureka:
  client:
    enabled: false
  instance:
    prefer-ip-address: true