spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  flyway:
    enabled: false

server:
  port: ${PORT:8083}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://ms-eureka:8761/eureka}
  instance:
    prefer-ip-address: true