spring.application.name=MicroVenta
spring.datasource.url=jdbc:mysql://localhost:3306/dbecomarket


spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
server.port=8085

#nivel de log global
#INFO WARN y ERROR
logging.level.root=INFO

#nivel de log para el paquete de la aplicacion
#DEBUG, informacion detallada para desarrollo y depuracion
#INFO, informacion general sobre el funcionamiento de la aplicacion
#WARN, advertencias sobre situaciones potencialmente problemáticas
#ERROR, errores que afectan el funcionamiento de la aplicacion
logging.level.com.example.demoBd=DEBUG

#formato del log, incluyendo timestamp, nivel de log, clase y mensaje
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n

#Nombre del archivo de log
logging.file.name=ecomarket.log

#Nivel de log para el archivo, en este caso se registra todo desde DEBUG en adelante
logging.level.file=INFO

#Nivel de log para el paquete de la aplicacion en el archivo, se puede configurar diferente al nivel de consola
logging.level.com.example.demoBd.file=DEBUG

#Formato del log para el archivo, similar al de la consola pero con un formato diferente si se desea
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss} %-5level %logger{36} - %msg%n
